### ISSUE TITLE
Gamefile local file implementation

### ISSUE THREAD

**Issue by jarradbattaglia** [ayaigame/ayai-backend#26]
Create structure of gamefile "files"

**Comment by kurtwheeler** [comment]
XPOST from the reddit thread:

I think that one file should probably be server configuration. Defining constants and setting general options.
I think that everything else should be organized into a rooms file, a npc file, an items file, a classes(mage, warrior, etc) file, etc.
Files could be broken up so that every single room won't have to be in one file. Something like:
"include_file": "some_dungeon.json"
could add all the rooms defined in some_dungeon.json to this rooms file.

Everything in the game files will be loaded into memory when the server is started and then won't be looked at again.
The only things loaded into memory from the database when the server is started will be ways in which the gamestate differs from what is represented in the game files. (Examples would be if a dragon is dead, the king has been succeeded by the prince, or other such irreversible changes.)
All other database loads will happen when a player logs in or performs certain actions. (i.e. searching for a chat log)
All constants will be defined in game files. (I think this will allow for the greatest flexibility when non-developers are trying to create games using our framework. Even if our editor doesn't allow every constant to be defined through the world editor a power user could actually dive into the game files to access more advanced options.)

**Comment by kurtwheeler** [comment]
This is ongoing but has a good start. Doesn't need to be an open issue.
